classdef Pose < robotics.ros.Message
    %Pose MATLAB implementation of localization/Pose
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'localization/Pose' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '686cdb55278463d2fa928851abbaaa00' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Pose_
        Covariance
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Covariance', 'Header', 'Pose_'} % List of non-constant message properties
        ROSPropertyList = {'covariance', 'header', 'pose'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Pose(msg)
            %Pose Construct the message object Pose
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'Pose', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function pose_ = get.Pose_(obj)
            %get.Pose_ Get the value for property Pose_
            javaArray = obj.JavaMessage.getPose;
            array = obj.readJavaArray(javaArray, 'single');
            pose_ = single(array);
        end
        
        function set.Pose_(obj, pose_)
            %set.Pose_ Set the value for property Pose_
            validateattributes(pose_, {'numeric'}, {'vector', 'numel', 3}, 'Pose', 'Pose_');
            
            javaArray = obj.JavaMessage.getPose;
            array = obj.writeJavaArray(pose_, javaArray, 'single');
            obj.JavaMessage.setPose(array);
        end
        
        function covariance = get.Covariance(obj)
            %get.Covariance Get the value for property Covariance
            javaArray = obj.JavaMessage.getCovariance;
            array = obj.readJavaArray(javaArray, 'single');
            covariance = single(array);
        end
        
        function set.Covariance(obj, covariance)
            %set.Covariance Set the value for property Covariance
            validateattributes(covariance, {'numeric'}, {'vector', 'numel', 9}, 'Pose', 'Covariance');
            
            javaArray = obj.JavaMessage.getCovariance;
            array = obj.writeJavaArray(covariance, javaArray, 'single');
            obj.JavaMessage.setCovariance(array);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Pose_ = obj.Pose_;
            cpObj.Covariance = obj.Covariance;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pose_ = strObj.Pose_;
            obj.Covariance = strObj.Covariance;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pose_ = obj.Pose_;
            strObj.Covariance = obj.Covariance;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.localization.Pose.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.localization.Pose;
            obj.reload(strObj);
        end
    end
end
